# Generated by Django 3.0.7 on 2020-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/%Y%m%d'),
        ),
    ]
